# Generated by Django 5.2.1 on 2025-06-03 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurses', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.CharField(help_text="What the patient needs, e.g., 'water', 'medication check'.", max_length=255)),
                ('patient_bed_number_snapshot', models.CharField(blank=True, help_text="Patient's bed number at time of request (for historical record).", max_length=10, null=True)),
                ('patient_name_snapshot', models.CharField(blank=True, help_text="Patient's name at time of request (for historical record).", max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING_ACCEPTANCE', help_text='Current status of the service request.', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('nurse', models.ForeignKey(blank=True, help_text='The nurse assigned to this request. Can be null if not yet assigned or nurse deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='nurses.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
